import os
import shutil
from pathlib import Path
from ultralytics import YOLO

# =====================================================================
# CONFIGURATION
# =====================================================================
# Path to the 'best.pt' file generated by your training script
MODEL_PATH = "./autolabel_project/initial_model/weights/best.pt" 

# Folder structures
UNLABELED_DIR = "./data/unlabeled"
AUTO_ACCEPTED_DIR = "./data/autolabeled_output/auto_accept"
HUMAN_REVIEW_DIR = "./data/autolabeled_output/human_review"

# Confidence Thresholds (Adjust these to fit your strictness)
HIGH_CONF_THRESH = 0.85  # ≥ 85% confidence: Auto-save raw images and labels
LOW_CONF_THRESH = 0.40   # 40% - 84% confidence: Send to human review folder

# =====================================================================
# INITIALIZATION
# =====================================================================
# Create output directories if they don't exist
os.makedirs(os.path.join(AUTO_ACCEPTED_DIR, "images"), exist_ok=True)
os.makedirs(os.path.join(AUTO_ACCEPTED_DIR, "labels"), exist_ok=True)
os.makedirs(HUMAN_REVIEW_DIR, exist_ok=True)

# Load your custom trained model
print(f"Loading custom model from {MODEL_PATH}...")
model = YOLO(MODEL_PATH)

# Grab all images from your unlabeled folder
image_extensions = (".jpg", ".jpeg", ".png", ".bmp", ".webp")
unlabeled_images = [
    f for f in os.listdir(UNLABELED_DIR) if f.lower().endswith(image_extensions)
]

print(f"Found {len(unlabeled_images)} unlabeled images. Starting autolabeling...\n")

# =====================================================================
# AUTOLABELING LOOP
# =====================================================================
for img_name in unlabeled_images:
    img_path = os.path.join(UNLABELED_DIR, img_name)
    
    # Run inference on the image
    results = model(img_path, verbose=False)[0]
    
    boxes = results.boxes
    if len(boxes) == 0:
        # No objects detected by the model; skips the image
        continue

    # Extract confidence scores for all objects detected in this single image
    confidences = boxes.conf.tolist()
    min_conf = min(confidences)
    max_conf = max(confidences)
    
    # Base filename without extension (e.g., 'image1' instead of 'image1.jpg')
    base_name = Path(img_name).stem
    
    # Tier 1: HIGH CONFIDENCE (Auto-Accept)
    # Every single detected object in the image is above your high threshold
    if min_conf >= HIGH_CONF_THRESH:
        # Copy original image to the auto-accepted images folder
        shutil.copy(img_path, os.path.join(AUTO_ACCEPTED_DIR, "images", img_name))
        
        # Save the annotations as a standard YOLO text file (.txt)
        label_file_path = os.path.join(AUTO_ACCEPTED_DIR, "labels", f"{base_name}.txt")
        results.save_txt(label_file_path)
        print(f"[AUTO-ACCEPTED] {img_name} (Min Conf: {min_conf:.2f})")
        
    # Tier 2: MEDIUM CONFIDENCE (Human Review)
    # At least one object fell below 85%, but the highest prediction is above 40%
    elif max_conf >= LOW_CONF_THRESH:
        # Save a visual plot (image with boxes drawn on it) so you can review it visually
        review_img_path = os.path.join(HUMAN_REVIEW_DIR, f"review_{img_name}")
        results.save(filename=review_img_path)
        
        # Save the raw .txt label file right next to it in case you want to import it to fix it
        raw_label_path = os.path.join(HUMAN_REVIEW_DIR, f"review_{base_name}.txt")
        results.save_txt(raw_label_path)
        print(f"[HUMAN REVIEW]  {img_name} (Max Conf: {max_conf:.2f})")
        
    # Tier 3: LOW CONFIDENCE (Rejected)
    else:
        print(f"[REJECTED]      {img_name} (Confidence too low: {max_conf:.2f})")

print("\nAutolabeling complete!")
print(f"--> Clean dataset ready for training: {AUTO_ACCEPTED_DIR}")
print(f"--> Images requiring quick human fix: {HUMAN_REVIEW_DIR}")